### ISSUE TITLE
Does this get the file extension or the file name?

### ISSUE THREAD

**Issue by programmeruser2** [zplusfour/file-string-tools#1]
I'm kind of confused here, since the package name indicates that the package gets the file extension but the actual implementation returns the file name.

**Comment by zplusfour** [comment]
Hi programmeruser
The first idea of this project was to get the file extension.
But then i changed the idea and the code, so the package name is wrong.

I'll create a class, and then add both functionality, like: `myClass.ext('hello.txt') // txt` and `myClass.name('hello.txt') // hello`
